### ISSUE TITLE
Error: No such module: evals

### ISSUE THREAD

**Issue by parmarmitesh** [twolfson/json-content-demux#2] opened 2020-06-30 08:07 UTC
I am using npm version:- 6.14.5 and node version:- 12.16.1
Following are steps to build and test the json-content-demux package:

git clone https://github.com/twolfson/json-content-demux.git
**npm install
npm test**

After performing **npm test**, I am getting following error, so can you help me please in this or suggest me steps if I missing something.:

Loading "test.js" tasks and helpers...ERROR
>> **Error: No such module: evals**
<WARN> Task "test" not found. Use --force to continue. </WARN>

Aborted due to warnings.
npm ERR! Test failed.  See above for more details.

**Comment by twolfson** [comment] 2020-06-30 08:16
Hmm, the issue is probably that the repo hasn't been updating a very long time so it's using a very old version of `grunt`, which likely has some broken dependencies by now

I'll triage the repo to see how much work this is going to be

**Comment by twolfson** [comment] 2020-06-30 08:16
Fwiw, the main library doesn't have this issue (in fact it has no dependencies) so it should work just fine

**Comment by twolfson** [comment] 2020-06-30 08:29
Alright, that was surprisingly easy. We swapped the test suite over to `nodeunit` and it's running/passing now. Released in `0.1.4`

Going to take the time to touch-up the rest of the repo now since I'm already here

**Comment by parmarmitesh** [comment] 2020-06-30 08:31
Can you provide the steps how to install/ configure the nodeunit?

**Comment by twolfson** [comment] 2020-06-30 08:32
Nothing to configure, you only need to update the repo:

- `git pull`
- `npm install`
- `npm test`

**Closed** 2020-06-30 08:39 UTC
